= Ch 3 - Operators

****
*OCP EXAM OBJECTIVES COVERED IN THIS CHAPTER:*

* *Using Operators and Decision Constructs*
* Use Java operators including the use of parentheses to override operator precedence
* *Working With Java Primitive Data Types and String APIs*
* Declare and initialize variables (including casting and promoting primitive
data types)
****

In general, three flavors of operators are available in Java: unary, binary, and ternary.

== OPERATOR PRECEDENCE

Unless overridden with parentheses, Java operators follow order of operation

|========================
|Operator | Symbols and examples
|Post-unary operators | expression++, expression--
|Pre-unary operators | ++expression, --expression
|Other unary operators | -, !, ~, +, (type)
|Multiplication/division/modulus | *, /, %
|Addition/subtraction | +, -
|Shift operators | <<, >>, >>>
|Relational operators | <, >, < =, >=, instanceof
|Equal to/not equal to | ==, !=
|Logical operators | &, ^, \|
|Short-circuit logical operators | &&, \|\|
|Ternary operators | boolean expression ? expression1 : expression2
|Assignment operators | =, +=, -=, *=, /=, %=, &=, ^=, \|=, <<=, >>=, >>>=
|========================

=== Example
One common practice in a certification exam, albeit less common in the real world, is to apply multiple increment or decrement operators to a single variable on the same line:

[source,java]
----
int lion = 3;
int tiger = ++lion * 5 / lion--;
System.out.println("lion is " + lion);
System.out.println("tiger is " + tiger);
----

This one is more complicated than the previous example because lion is modified two times on the same line. Each time it is modified, the value of lion changes, with different values being assigned to the variable. As you’ll recall from our discussion on operator precedence, order of operation plays an important part in evaluating this example. So how do you read this code? First, lion is decremented. We can simplify this:

[source,java]
----
int tiger = ++lion * 5 / 3; // lion assigned value of 2
----

Next, lion is incremented with the new value of 3 used in the expression, leading to this:

[source,java]
----
int tiger = 3 * 5 / 3; // lion assigned value of 3
----

Finally, we evaluate multiplication and division from left to right. The product of the first two numbers is 15. The divisor 3 divides 15 evenly, resulting in an assignment of 5 to tiger. The result is then printed:

lion is 3
tiger is 5

== Numeric Promotion Rules
1. If two values have different data types, Java will automatically promote one of the values to the larger of the two data types.
2. If one of the values is integral and the other is floating-point, Java will automatically promote the integral value to the floating-point value’s data
type.
3. Smaller data types, namely, byte, short, and char, are first promoted to int any time they’re used with a Java binary arithmetic operator, even if neither of the operands is int.
4. After all promotion has occurred and the operands have the same data type, the resulting value will have the same data type as its promoted
operands.
The last two rules are the ones most people have trouble with and the ones likely to trip you up on the exam. For the third rule, note that unary operators are excluded from this rule. For example, applying ++ to a short value results in a short value.

== Casting
Casting is a unary operation where one data type is explicitly interpreted as another data type.
Without casting, the compiler will generate an error when trying to put a larger data type inside a smaller one.

=== Overflow
Overflow is when a number is so large that it will no longer fit within the data type, so the system “wraps around” to the lowest negative value and counts up from there.

=== instanceOf

It is common to use casting and instanceof together when working with objects that can be various different types,

It is considered a good coding practice to use the instanceof operator prior to casting from one object to a narrower
type.

calling instanceof on the null literal or a null reference always returns false.


