= OCP JAVA 17 - EXAM TOPICS

== Handling date, time, text, numeric and boolean values

* Use primitives and wrapper classes including Math API, parentheses, type promotion, and casting to evaluate arithmetic and boolean expressions
* Manipulate text, including text blocks, using String and StringBuilder classes
* Manipulate date, time, duration, period, instant and time-zone objects using Date-Time API

== Controlling Program Flow

* Create program flow control constructs including if/else, switch statements and expressions, loops, and break and continue statements

== Utilizing Java Object-Oriented Approach

* Declare and instantiate Java objects including nested class objects, and explain the object life-cycle including creation, reassigning references, and garbage collection
* Create classes and records, and define and use instance and static fields and methods, constructors, and instance and static initializers
* Implement overloading, including var-arg methods
* Understand variable scopes, use local variable type inference, apply encapsulation, and make objects immutable
* Implement inheritance, including abstract and sealed classes. Override methods, including that of Object class. Implement polymorphism and differentiate object type versus reference type. Perform type casting, identify object types using instanceof operator and pattern matching
* Create and use interfaces, identify functional interfaces, and utilize private, static, and default interface methods
* Create and use enumerations with fields, methods and constructors

== Handling Exceptions

* Handle exceptions using try/catch/finally, try-with-resources, and multi-catch blocks, including custom exceptions

== Working with Arrays and Collections

* Create Java arrays, List, Set, Map, and Deque collections, and add, remove, update, retrieve and sort their elements

== Working with Streams and Lambda expressions

* Use Java object and primitive Streams, including lambda expressions implementing functional interfaces, to supply, filter, map, consume, and sort data
* Perform decomposition, concatenation and reduction, and grouping and partitioning on sequential and parallel streams

== Packaging and deploying Java code and use the Java Platform Module System

* Define modules and their dependencies, expose module content including for reflection. Define services, producers, and consumers
* Compile Java code, produce modular and non-modular jars, runtime images, and implement migration using unnamed and automatic modules

== Managing concurrent code execution

* Create worker threads using Runnable and Callable, manage the thread lifecycle, including automations provided by different Executor services and concurrent API
* Develop thread-safe code, using different locking mechanisms and concurrent API
* Process Java collections concurrently including the use of parallel streams

== Using Java I/O API

* Read and write console and file data using I/O Streams
* Serialize and de-serialize Java objects
* Create, traverse, read, and write Path objects and their properties using java.nio.file API

== Accessing databases using JDBC

* Create connections, create and execute basic, prepared and callable statements, process query results and control transactions using JDBC API

== Implementing Localization

* Implement localization using locales, resource bundles, parse and format messages, dates, times, and numbers including currency and percentage values

== Assume the following:

* Missing package and import statements: If sample code do not include package or import statements, and the question does not explicitly refer to these missing statements, then assume that all sample code is in the same package, or import statements exist to support them.
* No file or directory path names for classes: If a question does not state the file names or directory locations of classes, then assume one of the following, whichever will enable the code to compile and run:
** All classes are in one file
** Each class is contained in a separate file, and all files are in one directory
* Unintended line breaks: Sample code might have unintended line breaks. If you see a line of code that looks like it has wrapped, and this creates a situation where the wrapping is significant (for example, a quoted String literal has wrapped), assume that the wrapping is an extension of the same line, and the line does not contain a hard carriage return that would cause a compilation failure.
* Code fragments: A code fragment is a small section of source code presented without its context. Assume that all necessary supporting code exists and that the supporting environment fully supports the correct compilation and execution of the code shown and its omitted environment.
* Descriptive comments: Take descriptive comments, such as "setter and getters go here," at face value. Assume that correct code exists, compiles, and runs successfully to create the described effect.

== Candidates are also expected to:

* Understand the basics of Java Logging API.
* Use Annotations such as Override, Functionalnterface, Deprecated, SuppressWarnings, and SafeVarargs.
* Use generics, including wildcards.



=== var

Starting in Java 10, you have the option of using the keyword var instead
of the type for local variables under certain conditions. To use this feature,
you just type var instead of the primitive or reference type. Here’s an
example:
[source]
----
public void whatTypeAmI() {
var name = "Hello";
var size = 7;
}
----

Review of var Rules
We complete this section by summarizing all of the various rules for using
var in your code. Here’s a quick review of the var rules:
1. A var is used as a local variable in a constructor, method, or initializer
block.
2. A var cannot be used in constructor parameters, method parameters,
instance variables, or class variables.
3. A var is always initialized on the same line (or statement) where it is
declared.
4. The value of a var can change, but the type cannot.
5. A var cannot be initialized with a null value without a type.
6. A var is not permitted in a multiple-variable declaration.
7. A var is a reserved type name but not a reserved word, meaning it can be
used as an identifier except as a class, interface, or enum name.


==
Exam Essentials
Be able to recognize a constructor. A constructor has the same name as
the class. It looks like a method without a return type.
Be able to identify legal and illegal declarations and initialization.
Multiple variables can be declared and initialized in the same statement
when they share a type. Local variables require an explicit initialization;
others use the default value for that type. Identifiers may contain letters,
numbers, $, or _, although they may not begin with numbers. Also, you
cannot define an identifier that is just a single underscore character _.
Numeric literals may contain underscores between two digits, such as
1_000, but not in other places, such as _100_.0_. Numeric literals can
begin with 1–9, 0, 0x, 0X, 0b, and 0B, with the latter four indicating a
change of numeric base.
Be able to use var correctly. A var is used for a local variable inside a
constructor, a method, or an initializer block. It cannot be used for
constructor parameters, method parameters, instance variables, or class
variables. A var is initialized on the same line where it is declared, and
while it can change value, it cannot change type. A var cannot be
initialized with a null value without a type, nor can it be used in multiple
variable declarations. Finally, var is not a reserved word in Java and can
be used as a variable name.
Be able to determine where variables go into and out of scope. All
variables go into scope when they are declared. Local variables go out of
scope when the block they are declared in ends. Instance variables go out
of scope when the object is eligible for garbage collection. Class variables
remain in scope as long as the program is running.
Know how to identify when an object is eligible for garbage collection.
Draw a diagram to keep track of references and objects as you trace the
code. When no arrows point to a box (object), it is eligible for garbage
collection.


== Switch
The following is a list of all data types supported by switch statements:
* int and Integer
* byte and Byte
* short and Short
* char and Character
* String
* enum values
* var (if the type resolves to one of the preceding types)
For the exam, we recommend you memorize this list. Remember,
boolean, long, float, double, and each of their associated wrapper
classes are not supported by switch statements.